ishop/ishop/ishop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from myapp.views import RegisterFormView, home, LoginFormView, LogoutFormView, CreateTovar\
    , TovarListView, TovarUpdateView, CreatePurchase


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('register/', RegisterFormView.as_view(), name='register'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', LogoutFormView.as_view(), name='logout'),
    path('create/', CreateTovar.as_view(), name='create'),
    path('see/', TovarListView.as_view(), name='see'),
    path('update/<int:pk>/', TovarUpdateView.as_view(), name='update'),
    path('buy/', CreatePurchase.as_view(), name='buy'),
]

ishop/ishop/myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime, date, time, timedelta


GENDER = (
    ('Man', 'Man'),
    ('Woman', 'Woman'),
    ('Unknown', 'Unknown')
)


class MyUser(AbstractUser):
    purse = models.DecimalField(default=10000.00, max_digits=7, decimal_places=2, verbose_name="Кошелёк")
    birthday = models.DateTimeField(verbose_name="Дата рождения", default=datetime.now()-timedelta(days=10957.5))
    gender = models.CharField(choices=GENDER, max_length=10, default='Unknown')

    def __str__(self):
        return "Пользователь {}".format(self.username)


class Tovar(models.Model):
    name = models.CharField(max_length=5000, default="Название товара", verbose_name="Название")
    description = models.TextField(default="Описание товара", verbose_name="Описание")
    price = models.DecimalField(default=0, max_digits=7, decimal_places=2, verbose_name="Цена товара")
    number = models.PositiveSmallIntegerField(default=0, verbose_name="Количество на складе")

    class Meta:
        ordering = ['id']

    def __str__(self):
        return "Товар {}, pk {}, цена {} грн.".format(self.name, self.pk, self.price)


class Purchase(models.Model):
    buyer = models.ForeignKey(to=MyUser, on_delete=models.CASCADE, verbose_name="Покупатель", default=None)
    article = models.ForeignKey(to=Tovar, on_delete=models.DO_NOTHING, verbose_name="Товар", default=None)
    article_number = models.PositiveSmallIntegerField(default=0, verbose_name="Количество")
    purchase_date = models.DateTimeField(verbose_name="Дата и время покупки", auto_now_add=True)


class Vozvrat(models.Model):
    item = models.ForeignKey(to=Purchase, on_delete=models.CASCADE, verbose_name="Товар к возврату", default=None)
    request_time = models.DateTimeField(verbose_name="Дата запроса", auto_now_add=True)

    def __str__(self):
        return "Товар {} возвращает покупатель {}".format(self.item.article.name, self.item.buyer.username)

ishop/ishop/myapp/forms.py
from datetime import datetime, date, time, timedelta
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyUser, GENDER, Tovar, Purchase, Vozvrat


class MyForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Введите e-mail в формате "mylogin@mymail.com"')
    first_name = forms.CharField(max_length=200, label='Имя')
    last_name = forms.CharField(max_length=200, label='Фамилия')
    birthday = forms.DateField(label='Дата рождения', required=False, input_formats=['%d/%m/%Y'])
    gender = forms.CharField(max_length=10, label='Пол', widget=forms.RadioSelect(choices=GENDER), required=False)
    username = forms.CharField(max_length=150, label='Логин')

    class Meta:
        model = MyUser
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'gender', 'email')
        widgets = {
            'birthday': forms.DateInput(attrs={'class': 'date_picker'})
        }


class CreateTovarForm(forms.ModelForm):
    class Meta:
        model = Tovar
        fields = '__all__'


class UpdateTovarForm(forms.ModelForm):
    class Meta:
        model = Tovar
        fields = ('name', 'description', 'price', 'number')


class CreatePurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('article_number', )

ishop/ishop/myapp/views.py
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, FormView, UpdateView, CreateView
# from django.views.generic.edit import FormView, UpdateView, CreateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LogoutView, LoginView
from .models import Tovar, Purchase, Vozvrat, MyUser
from .forms import MyForm, CreateTovarForm, UpdateTovarForm, CreatePurchaseForm
from django.shortcuts import render


def home(request):
    return render(request, template_name="home.html")


class RegisterFormView(FormView):
    # form_class = UserCreationForm
    form_class = MyForm
    success_url = "/login/"
    template_name = "login/register.html"

    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()
        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)


"""Если для регистрации достаточно только логина и пароля, файл forms.py не нужно создавать, 
в классе class RegisterFormView(FormView) заменить form_class = UserCreationForm,
и соответственно не импортировать MyForm, но обязательно from django.contrib.auth.forms import UserCreationForm"""


class LoginFormView(LoginView):
    form_class = AuthenticationForm
    template_name = "login/login.html"


class LogoutFormView(LogoutView):
    next_page = "/"


class CreateTovar(CreateView):
    model = Tovar
    form_class = CreateTovarForm
    success_url = '/create/'
    template_name = 'tovar/tovar_add.html'


class TovarUpdateView(UpdateView):
    template_name = 'tovar/tovar_update.html'
    form_class = UpdateTovarForm
    success_url = '/see/'
    model = Tovar


class TovarListView(ListView):
    model = Tovar
    paginate_by = 5
    template_name = 'tovar/tovar_see.html'
    # success_url = '/see/'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context.update(
            {'tovar_create_form': CreateTovarForm,
             'tovar_update_form': UpdateTovarForm}
        )
        return context


class CreatePurchase(CreateView):
    model = Purchase
    form_class = CreatePurchaseForm
    success_url = '/see/'
    template_name = 'tovar/tovar_buy.html'

ishop/ishop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Template</title>
</head>
<body>
<header><a href="{% url 'home' %}">На главную</a><br>
{% if user.is_authenticated %}
    <p>Вы на сайте под именем "{{user.username}}", id "{{user.id}}", сумма в кошельке {{user.purse}} грн.</p>
    <p>Пользователь зарегистрирован {{user.date_joined}} Последний вход {{user.last_login}}</p>
    <p>Дата рождения пользователя {{user.birthday}}</p>
    <a href="{% url 'logout' %}">Выйти из учётной записи</a>
{% else %}
    <a href="{% url 'login' %}">Войти (для зарегистрированных пользователей)</a> / <a href="{% url 'register' %}">Зарегистрироваться</a>
{% endif %}
</header>
  {% block content %}
  {% endblock %}

{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
</body>
</html>

ishop/ishop/templates/home.html
<title>Homepage</title>
{% extends 'base.html' %}

{% block content %}
<h3>Интернет-магазин</h3>
<a href ="{% url 'see' %}">Просмотр товаров</a>
{% if user.is_superuser %}
<a href ="{% url 'create' %}">Добавление товара</a>
{% endif %}
{% endblock %}

ishop/ishop/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% if form.errors %}
    <p style="color: red">Неправильное имя пользователя или пароль.</p>
  {% endif %}
<form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Войти на сайт</button>
</form>
<br>
<a href="{% url 'home' %}">На главную</a>

ishop/ishop/templates/login/register.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
</head>
<body>
<form action="" method="post">
      {% csrf_token %}
<!--      &lt;!&ndash; as_p для того, чтобы каждый элемент формы был с новой строки &ndash;&gt;-->
<!--      {{ form.as_p }}-->

{% for field in form %}
    <p>
        {% if field == form.birthday %}
        {{ field.label_tag }}
        {{form.birthday}}
        <script>
          $(function () {
            $("#id_birthday").datepicker({
              format:'dd/mm/yyyy',
              weekStart: 1
            });
          });
        </script>
        {% else %}
        {{ field.label_tag }}
        {{ field }}
        {% endif %}

        {% if field.help_text %}
        <div style="color: grey">{{ field.help_text | safe }}</div>
        {% endif %}
        {% for error in field.errors %}
        <p style="color: red">{{ error | safe }}</p>
        {% endfor %}
    </p>
    {% endfor %}
      <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>

ishop/ishop/templates/tovar/tovar_add.html
<title>Добавление товара</title>
{% extends 'base.html' %}

{% block content %}
<h3>Добавление товара</h3>
<form method="post" action="{% url 'create' %}">
    {% csrf_token %}
    {{ form.as_ul }}
    <input type="submit" value="Создать товар">
</form>
{% include 'tovar/tovar_list.html' %}
<div>
    {% for tovar in object_list %}
    {{tovar.id}}{{tovar.name}}{{tovar.description}}{{tovar.price}}{{tovar.mumber}}<br>
    {% endfor %}
</div>
{% endblock %}

ishop/ishop/templates/tovar/tovar_buy.html
<title>Покупка товара</title>
{% extends 'base.html' %}

{% block content %}
<h3>Добавление товара</h3>

<form method="post" action="">
    {% csrf_token %}
    <p>Введите количество</p>{{ form.article_number}}
    <input type="submit" value="В корзину">
</form>
{% endblock %}

ishop/ishop/templates/tovar/tovar_list.html
<!--{% block content %}-->
<h3>Просмотр товаров</h3>
<div>
    {% for tovar in object_list %}
    {{tovar.id}}{{tovar.name}}{{tovar.description}}{{tovar.price}}{{tovar.mumber}}<br>
    {% endfor %}
</div>
<!--{% endblock %}-->

ishop/ishop/templates/tovar/tovar_see.html
<title>Просмотр товаров</title>
{% extends 'base.html' %}

{% block content %}

<h3>Просмотр товаров</h3>
{% for tovar in object_list %}
<div>Код {{tovar.pk}}. Название товара "{{tovar.name}}". {{tovar.description}} Цена {{tovar.price}} Доступно {{tovar.number}}

    {% if user.is_authenticated %}
<form method="post" action="{% url 'buy' %}">
    {% csrf_token %}
    {{ form.article_number}}
    <input type="submit" value="Купить">
</form>
        {% if user.is_superuser %}
        <a href="{% url 'update' tovar.pk %}" target="_blank">Обновить</a>
        {% endif %}
    {% endif %}
</div>    <br>
{% endfor %}
{% endblock %}

ishop/ishop/templates/tovar/tovar_update.html
<title>Изменение товара</title>
{% extends 'base.html' %}

{% block content %}
<h3>Изменение товара</h3>
<!--<form method="post">-->
<form method="post" action="{% url 'update' pk=tovar.pk %}" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Обновить">
</form>
{% endblock %}

ishop/ishop/templates/tovar/tovar_vozvrat.html
<title>Возврат товара</title>
{% extends 'base.html' %}

{% block content %}
<h3>Возврат товара</h3>
{% endblock %}